<?php
$labels = array();
$labels['quota_plugin_title'] = 'Mailbox Quota';
$labels['chart_title'] = 'Mailbox Quota Chart';
$labels['space_used'] = 'Mailbox Quota Used';
$labels['space_free'] = 'Mailbox Quota Free';
$labels['quota_meet_90'] = 'You have used over 90% of your storage quota.';
$labels['quota_meet_99'] = 'You have used over 99% of your storage quota.';
$labels['problem_please_contact'] = 'If you have any issues, please contact %s.';
$labels['unknown'] = 'unknown';
